name: check_duplicate_words
on: push

jobs:
  build:
    name: Check
    runs-on: ubuntu-18.04
    steps:
      - run: find . -name '*.md' -type f -print0 | xargs -0 -I {} sh -c 'cat "{}"' | grep ':' | grep -v 'https' | awk '{sub(":.*", "");print $0;}' | sort | uniq -d
